# Generated by Django 3.0.8 on 2020-08-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200808_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_front_url',
            field=models.URLField(default=''),
        ),
    ]
