version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: pur_beurre
          POSTGRES_DB: pur_beurre      
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: cd pur_beurre && ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
