version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/pur_beurre?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: pur_beurre
          POSTGRES_DB: pur_beurre
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: install xvfb
          command: |
            sudo apt-get update -q &&
            sudo apt-get install -q -y unzip xvfb firefox-esr
      - restore_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - '.venv'
            - '/usr/local/bin'
            - '/usr/local/lib/python3.6/site-packages'
      - python/load-cache
      - python/install-deps
      - python/save-cache            
      - run: echo cd pur_beurre/driver && tar xvzf geckodriver-v0.27.0-linux64.tar.gz geckodriver
      - run: echo cd pur_beurre/user/tests && cp ubuntu_test_ux_user.py test_ux_user.py
      - run: echo cd pur_beurre/user/tests && cp ubuntu_test_ux_user.py test_ux_user.py
      - run: echo cho nohup Xvfb :99 -screen 0 1280x1024x24 esperluete
      - run:
          command: export DJANGO_SETTINGS_MODULE=pur_beurre.settings && cd pur_beurre && python ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
